/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://hyruwn3ikfhwngxbziodwcv6lq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XxhiLNS7B",
    "aws_user_pools_web_client_id": "55c5t3jsdquruclci6ubna607h",
    "oauth": {}
};


export default awsmobile;
